# Generated by Django 2.2.9 on 2020-03-07 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_userliked'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('comment_id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('comment', models.TextField(max_length=500)),
            ],
        ),
    ]
